version: '{build}'
image: Visual Studio 2015

install:
  - set QTDIR=C:\Qt\5.9.2\mingw53_32
  - set BOOST_PATH=C:\Libraries\boost_1_63_0
  - set PATH_ORIG=%PATH%
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
build_script:
  - set BITBAYPATH=%cd%
  - cd %BOOST_PATH%
  - cd tools\build
  - .\bootstrap.bat gcc
  - .\b2.exe install toolset=gcc --prefix=%BOOST_PATH%\b2_mingw
  - cd ..
  - cd ..
  - set PATH=%PATH%;%BOOST_PATH%\b2_mingw\bin
  - b2 toolset=gcc --build-type=complete link=static threading=multi variant=release --layout=tagged stage --with-system --with-filesystem --with-program_options --with-thread --with-chrono
  - ls stage\lib
  - cd %BITBAYPATH%
  - curl -fsSL -o static_db_4_8_win.zip https://github.com/bitbaymarket/bitbay-prebuilt-libs1/releases/download/1/static_db_4_8_win.zip
  - 7z x static_db_4_8_win.zip > nul
  - move static_db_4_8_win db
  - curl -fsSL -o static_openssl_win.zip https://github.com/bitbaymarket/bitbay-prebuilt-libs1/releases/download/1/static_openssl_win.zip
  - 7z x static_openssl_win.zip > nul
  - move static_openssl_win openssl
  - curl -fsSL -o static_miniupnpc_win.zip https://github.com/bitbaymarket/bitbay-prebuilt-libs1/releases/download/1/static_miniupnpc_win.zip
  - 7z x static_miniupnpc_win.zip > nul
  - move static_miniupnpc_win miniupnpc
  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%QTDIR%\bin
  - qmake CICD=appveyor \
        BOOST_INCLUDE_PATH=%BOOST_PATH% BDB_INCLUDE_PATH=%cd%\db\include BDB_LIB_PATH=%cd%\db OPENSSL_INCLUDE_PATH=%cd%\openssl\include BOOST_LIB_PATH=%BOOST_PATH%\stage\lib MINIUPNPC_LIB_PATH=%cd%\miniupnpc OPENSSL_LIB_PATH=%cd%\openssl bitbay-qt.pro
  - make -j2
  - cd release
  - rm -f qrc_bitcoin.cpp
  - windeployqt bitbay-wallet-qt.exe --no-translations --no-system-d3d-compiler --no-webkit2 --no-angle
  - dir
  - cd ..
  - set PATH=%PATH_ORIG%
  - 7z a bitbay-qt_win32.zip release

test: off

#artifacts:
#  - path: bitbay-qt_win32.zip
#    name: bitbay-qt_win32.zip
