language: cpp
os:
- osx
osx_image: xcode7.3
dist: trusty
compiler:
- clang
env:
  matrix:
  - QT=510 BREW=@5.10
install:
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install boost || echo -'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install openssl || echo -'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install miniupnpc'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt$BREW'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'
- qmake -v
before_script:
- '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
- cd "$TRAVIS_BUILD_DIR"
- qmake "CICD=travis_mac" bitbay-qt.pro
script:
- cd "$TRAVIS_BUILD_DIR"
- curl -fsSL -o db-4.8.30.NC.tar.gz http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
- tar -zxf db-4.8.30.NC.tar.gz
- mv db-4.8.30.NC db
- cd db
- patch dbinc/atomic.h < ../doc/mac_db-4.8_atomic.patch
- cd build_unix
- CFLAGS="-mmacosx-version-min=10.9" CXXFLAGS="-mmacosx-version-min=10.9" sh ../dist/configure
  --enable-cxx --prefix=`pwd`/inst
- make -j2
- make install
- cd ..
- cd ..
- make -j2
- cd src
- make -j2 -f makefile.osx
- cd ..
- cp src/bitbayd BitBay-Wallet-Qt.app/Contents/MacOS/
- macdeployqt BitBay-Wallet-Qt.app -verbose=2 -executable=BitBay-Wallet-Qt.app/Contents/MacOS/bitbayd
- otool -L BitBay-Wallet-Qt.app/Contents/MacOS/BitBay-Wallet-Qt
- otool -L BitBay-Wallet-Qt.app/Contents/MacOS/bitbayd
- install_name_tool -change /usr/local/Cellar/openssl/1.0.2l/lib/libcrypto.1.0.0.dylib
  @executable_path/../Frameworks/libcrypto.1.0.0.dylib BitBay-Wallet-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
- ls
- zip -r bitbay-wallet-qt_mac.zip BitBay-Wallet-Qt.app
deploy:
  provider: releases
  api_key:
    secure: pLwB88n+hu56NAojvbdCcbzf80LiWKNAD4jlpQdXLisM/9pFQlyjZGo1mwyY7Sy4DuouCWkoWB895flsnBH2sVQzeJhXE9Jb3cTx8VGMlOTTeMqDcJJSswTpqf8MBXwQKAVOjhQIRBDZ27q/5+KRT3TaK9MrNmW2ul+PaGI1PWGvq5Qer9wNgqGIf9sDHIPhdG46YNa9eXzdq/e8xpD6kUxUWFoSx8w6w8mBAGXcKCpxZQqEZs1V9HUDo+a+x69fJFiA8qN9OsfbIeN7NG22/2Ahw9SUw/nYa5JLokbLLFG5wIpKh4u8/7zFTOuWiHz+A64kLaanlMjIM1otz1aS3/iOsd6LZ7bhtTCLYGMsjvGnkhlXwO45hdUHz5YeTY4/oM6yC8mB5VYvPiSsTtgu/C9brydo2a6KXc6yfYkHjEX0AD5E4QwnZAVAyjsIP+0jR+0Ljs3Nh/VfU16kBclIj6lnv2sjYxetMgPkk29HlelUEa/WL/IUhWzlL1/M2a2vwI/aCg3c7niLmmYLIo1dd8pt0GVxfqQVVGGGHXOH9LyCR4x3A6wZKaLDEKc8VArWJl+jRtqltrrxQuY9W8Vw7pbphgeORpoOVZ3lbWZrhr5aiMicYEPHYJ7Yd7bItLxX8wiyMdkK13cgLU9z6s24SVqK5cxgsbnANM1LEIfwPjA=
  file: $TRAVIS_BUILD_DIR/bitbay-wallet-qt_mac.zip
  skip_cleanup: true
  on:
    tags: true
