language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: ARCH="x86"
    - os: osx
      osx_image: xcode7.2
      compiler: clang

install:
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install boost || echo -'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install openssl || echo -'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install miniupnpc'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt$BREW'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'
- qmake -v
before_script:
- '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
script:
- >
  if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    sudo add-apt-repository -y ppa:beineri/opt-qt593-trusty;
    sudo add-apt-repository -y ppa:bitcoin/bitcoin;
    sudo apt-get update;
    if [[ $ARCH == "x86" ]]; then
      sudo apt-get install -y libdb4.8-dev;
      sudo apt-get install -y libdb4.8++-dev;
      sudo apt-get install -y libboost-filesystem-dev;
      sudo apt-get install -y libboost-program-options-dev;
      sudo apt-get install -y libboost-thread-dev;
      sudo apt-get install -y libssl-dev;
      sudo apt-get install -y libminiupnpc-dev;
      sudo apt-get install -y qt59-meta-minimal;
      sudo apt-get install -y qt59tools;
    else
      sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib;
      sudo apt-get install -y libdb4.8-dev:i386;
      sudo apt-get install -y libdb4.8++-dev:i386;
      sudo apt-get install -y libboost-filesystem-dev:i386;
      sudo apt-get install -y libboost-program-options-dev:i386;
      sudo apt-get install -y libboost-thread-dev:i386;
      sudo apt-get install -y libssl-dev:i386;
      sudo apt-get install -y libminiupnpc-dev:i386;
      sudo apt-get install -y qt59-meta-minimal:i386;
      sudo apt-get install -y qt59tools:i386;
    fi;
    source /opt/qt59/bin/qt59-env.sh;
    export;
  else
    cd "$TRAVIS_BUILD_DIR";
    curl -fsSL -o db-4.8.30.NC.tar.gz https://github.com/bitbaymarket/bitbay-prebuilt-libs1/releases/download/base1/db-4.8.30.NC.tar.gz;
    tar -zxf db-4.8.30.NC.tar.gz;
    mv db-4.8.30.NC db;
    cd db;
    patch dbinc/atomic.h < ../doc/mac_db-4.8_atomic.patch;
    cd build_unix;
    CFLAGS="-mmacosx-version-min=10.9" CXXFLAGS="-mmacosx-version-min=10.9" sh ../dist/configure --enable-cxx --prefix=`pwd`/inst;
    make -j2;
    make install;
    cd ..;
    cd ..;
  fi;

- qmake -v
- cd "$TRAVIS_BUILD_DIR"
- qmake "CICD=travis_mac" bitbay-qt.pro
- make -j2
- cd src
- >
  if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    make -j2 -f makefile.unix;
  else
    make -j2 -f makefile.osx;
    cd ..
    cp src/bitbayd BitBay-Wallet-Qt.app/Contents/MacOS/
    macdeployqt BitBay-Wallet-Qt.app -verbose=2 -executable=BitBay-Wallet-Qt.app/Contents/MacOS/bitbayd
    otool -L BitBay-Wallet-Qt.app/Contents/MacOS/BitBay-Wallet-Qt
    otool -L BitBay-Wallet-Qt.app/Contents/MacOS/bitbayd
    install_name_tool -change /usr/local/Cellar/openssl/1.0.2l/lib/libcrypto.1.0.0.dylib \
      @executable_path/../Frameworks/libcrypto.1.0.0.dylib BitBay-Wallet-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib;
    ls;
    zip -r bitbay-wallet-qt_mac.zip BitBay-Wallet-Qt.app;
  fi;
