language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
      compiler: clang

install:
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install boost || echo -'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install openssl || echo -'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install miniupnpc'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt$BREW'
- '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'
- qmake -v
before_script:
- '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
- cd "$TRAVIS_BUILD_DIR"
- qmake "CICD=travis_mac" bitbay-qt.pro
script:
- cd "$TRAVIS_BUILD_DIR"
- curl -fsSL -o db-4.8.30.NC.tar.gz http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
- tar -zxf db-4.8.30.NC.tar.gz
- mv db-4.8.30.NC db
- cd db
- patch dbinc/atomic.h < ../doc/mac_db-4.8_atomic.patch
- cd build_unix
